version: '3'
services:
    cars:
        build: .
        command: python app.py
        ports:
            - "80:5000"
        volumes:
        - .:/app
        container_name: andriusma_service
        networks:
            - ws_bridge
    movies:
        build: .
        command: python Danno/cinema.py
        ports:
            - "9999:9999"
        volumes:
        - .:/app
        container_name: external
        networks:
            - ws_bridge
networks:
    ws_bridge: